name: Docker

on:
  push:
    branches:
      - '**'        # matches every branch

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run the Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build . -t tex2scs:latest
          mkdir ./kb-translated
          docker run --rm -v ${PWD}/kb/docs/sc-network:/kb -v ${PWD}/kb-translated:/kb-translated tex2scs:latest
